// frontend-daisyui/app/routes/dashboard.tsx
import { useNavigate } from 'react-router';
import { useAuthStore } from '~/stores/auth.store';
import { useEffect } from 'react';

export function meta() {
  return [
    { title: "Dashboard - PocketBase App" },
    { name: "description", content: "User Dashboard" },
  ];
}

export default function Dashboard() {
  const navigate = useNavigate();
  const { user, isAuthenticated, logout } = useAuthStore();

  useEffect(() => {
    if (!isAuthenticated) {
      navigate('/');
    }
  }, [isAuthenticated, navigate]);

  const handleLogout = async () => {
    await logout();
    navigate('/');
  };

  if (!user) {
    return null;
  }

  return (
    <div className="min-h-screen bg-base-200">
      <div className="navbar bg-base-100 shadow-lg">
        <div className="flex-1">
          <a className="btn btn-ghost text-xl">Dashboard</a>
        </div>
        <div className="flex-none gap-2">
          <div className="dropdown dropdown-end">
            <div className="flex items-center gap-4">
              <span className="text-sm">Welcome, {user.email}</span>
              <button onClick={handleLogout} className="btn btn-sm btn-outline">
                Logout
              </button>
            </div>
          </div>
        </div>
      </div>

      <div className="container mx-auto p-8">
        <div className="card bg-base-100 shadow-xl">
          <div className="card-body">
            <h2 className="card-title">Welcome to your Dashboard!</h2>
            <p>You are successfully logged in.</p>
            <div className="divider"></div>
            <div>
              <h3 className="font-semibold mb-2">User Details:</h3>
              <p>Email: {user.email}</p>
              <p>ID: {user.id}</p>
              <p>Created: {new Date(user.created).toLocaleDateString()}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// frontend/src/routes/dashboard/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { goto } from '$app/navigation';
  import pb from '$lib/pocketbase';
  import { currentUser } from '$lib/stores/auth';

  $: user = $currentUser;

  onMount(() => {
    if (!$currentUser) {
      goto('/');
    }
  });

  function handleLogout() {
    pb?.authStore.clear();
    goto('/');
  }
</script>

{#if user}
  <div class="min-h-screen bg-base-100">
    <div class="navbar bg-base-200">
      <div class="flex-1">
        <a href="/dashboard" class="btn btn-ghost text-xl">Dashboard</a>
      </div>
      <div class="flex-none gap-4">
        <span class="text-sm">Welcome, {user.email}</span>
        <button class="btn btn-outline btn-sm" on:click={handleLogout}>
          Logout
        </button>
      </div>
    </div>

    <div class="container mx-auto px-4 py-8">
      <h1 class="text-3xl font-bold mb-8">Dashboard</h1>
      
      <div class="card bg-base-100 shadow-xl">
        <div class="card-body">
          <h2 class="card-title">User Information</h2>
          <div class="space-y-2">
            <p><strong>Email:</strong> {user.email}</p>
            <p><strong>ID:</strong> {user.id}</p>
            <p><strong>Created:</strong> {new Date(user.created).toLocaleDateString()}</p>
          </div>
        </div>
      </div>
    </div>
  </div>
{/if}
